### ISSUE TITLE
Instance has no 'disconnect' member

### ISSUE THREAD

**Issue by Smart-Stadium** [DatavenueLiveObjects/LiveObjects_SDK_for_Python#1]
Hello @Kacp3r3 and @krzysztofkrzeslak, 

I'm trying to use this SDK by following the ReadMe file. 
You mentionned the disconnect() method in the "Connect, disconnect and loop" part. 
Unfortunately I can't manage to find the function definition neither in the Connection.py file nor in the tutorials provided. 

Any help please? 
Thanks in advance,

Aurelie

**Comment by Kacp3r3** [comment]
Hi, sorry to mislead you. I have added this missing function.

**Comment by Smart-Stadium** [comment]
No worries, just updated my code. Works perfectly, thanks.
